_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.11.9
        t:
            "1":
                - 1
                - 41
                - 49
                - 55
                - 63
                - 74
            "2":
                - 1
                - 41
                - 49
                - 55
                - 63
                - 74
            "3":
                - 1
                - 16
                - 23
                - 55
            "4": 3.11.9
            "5": 0.19.8
            "8":
                - 3
                - 5
            "12": 0.19.8
            "13": windows-amd64
data:
    value:
        batch_size: 8
        img_dir: C:/Users/danie/OneDrive/Desktop/INM705/archive/Montgomery/MontgomerySet/CXR_png
        mask_dir: "C:/Users/danie/OneDrive/Desktop/INM705\archive/Montgomery/MontgomerySet/masks"
model:
    value:
        classes: 1
        encoder_name: resnet34
        encoder_weights: imagenet
        in_channels: 3
training:
    value:
        device: cuda
        epochs: 10
        lr: 0.0001
